apiVersion: v1
kind: Service
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: todo-app
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo-app
        tier: frontend
    spec:
      containers:
      - image: elementalnet/angularjs-todo-app:latest
        imagePullPolicy: Always
        name: todo-app
        env:
        - name: DB_HOST
          value: todo-app-mysql
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-app-mysql-password
              key: password
        ports:
        - containerPort: 80
          name: todo-app
